on:
  push:
    branches:
      - main
name: Publish to NPM
permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js 18
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18.x'
          always-auth: true
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
          yarn config set npmAlwaysAuth true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn npm publish --access public
